# In order for builds to pass, in CircleCI you must have following environment variables setub:
# POSTMARK_API_KEY,POSTMARK_ACCOUNT_API_KEY,POSTMARK_CI_RECIPIENT,POSTMARK_CI_SENDER

version: 2.1

workflows:
  ruby-tests:
    jobs:
      - unit-tests:
          matrix:
            parameters:
              version: [
                "circleci/ruby:2",
                "circleci/ruby:2.1",
                "circleci/ruby:2.2",
                "circleci/ruby:2.3",
                "circleci/ruby:2.4",
                "circleci/ruby:2.5",
                "circleci/ruby:2.6",
                "circleci/ruby:2.7"
              ]
      - unit-tests-legacy:
          matrix:
            parameters:
              version: [
                "kneip/ree-1.8.7-2012.02",
                "ruby:1.9.3",
                "circleci/jruby:9"
              ]

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  unit-tests:
    parallelism: 1
    parameters:
      version:
        type: string
    docker:
      - image: << parameters.version >>
    steps:
      - checkout
      - check_version

      - run:
          name: Install dependencies
          command: bundle install

      - run_tests

  unit-tests-legacy:
    parallelism: 1
    environment:
      BUNDLE_GEMFILE: ./gemfiles/Gemfile.legacy
    parameters:
      version:
        type: string
    docker:
      - image: << parameters.version >>
    steps:
      - checkout
      - check_version

      - run:
          name: Install dependencies
          command: |
            gem install bundler --version 1.17.3
            bundle install

      - run_tests

commands:
  check_version:
    steps:
      - run:
          name: Check Ruby version
          command: |
            echo "ruby: $(ruby --version)"
  run_tests:
    steps:
      - run:
          name: Run tests
          command: bundle exec rake spec
      - store_test_results:
          path: test-results
